apiVersion: v1
kind: Secret
metadata:
    name: mongodb-secret
type: Opaque
data:
    mongo-root-username: dXNlcm5hbWU= #FOR THIS IN TERMINAL #echo -n 'username' | base64 FOR ENCODING THE USERNAME 
    mongo-root-password: cGFzc3dvcmQ= #FOR THIS IN TERMINAL #echo -n 'password' | base64 FOR ENCODING THE PASSWORD 
